on:
  push:
    branches: 
      - develop/*/*
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    outputs:
      envName: ${{ steps.build2.outputs.envName }}
    steps:
    - name: "build"
      shell: powershell
      run: |
        echo "test"2
        echo "envName=DEV_DIG" >> "$env:GITHUB_OUTPUT"
# 
  deployment:
    runs-on: windows-latest
    needs: build
    environment: ${{ needs.build.outputs.envName }}
    steps:
    - name: "Deploy"
      shell: powershell
      run: |
        echo "${{ needs.build.outputs.envName }}"
        echo "${{ vars.DB_NAME }}"
      # env:
      #   DB_NAME: ${{ vars.DB_NAME }}
