on:
  push:
    branches: 
      - develop/*/*
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  db_name: ${{ vars.DB_NAME }}
  
jobs:
  build:
    runs-on: windows-latest
    outputs:
      envName: ${{ steps.build.outputs.envName }}
    steps:
    - name: "build"
      shell: powershell
      run: |
        echo "test"
        echo "envName=DEV_DIG" >> "$env:GITHUB_OUTPUT"

  deployment:
    runs-on: windows-latest
    needs: build
    environment: ${{ needs.build.outputs.envName }}
    steps:
    - name: "Deploy"
      shell: powershell
      run: |
        echo "${{ vars.DB_NAME }}"
      # env:
      #   DB_NAME: ${{ vars.DB_NAME }}
