on:
  push:
    branches: 
      - develop/*/*
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    outputs:
      envName: ${{ steps.build2.outputs.envName }}
    steps:
    - name: "build2"
      shell: powershell
      run: |
        echo "test"
        echo "envName=devv" >> "$env:GITHUB_OUTPUT"
        Get-Content "$env:GITHUB_OUTPUT"
    - name: "build3"
      shell: powershell
      run: |
        echo "test"
        echo "${{ steps.build2.outputs.envName }}"
# 
  deployment:
    runs-on: windows-latest
    needs: [ build ]
    environment: ${{ needs.build.outputs.envName }}
    steps:
    - name: "Deploy"
      shell: powershell
      run: |
        echo "${{ needs.build.outputs.envName }}"
        echo "${{ vars.DB_NAME }}"
      # env:
      #   DB_NAME: ${{ vars.DB_NAME }}
